service: cloudone-fss-gcp-teams-notifications

custom:
  defaultStage: prod

params:
  prod:
    TEAMS_URL: <TEAMS_URL>
    DEPLOYMENT_REGION: <GCP_DEPLOYMENT_REGION>
    GCP_PROJECT_ID: <PROJECT_ID>
    EVENT_TYPE: providers/cloud.pubsub/eventTypes/topic.publish
    TRIGGER_RESOURCE: projects/<PROJECT_ID>/topics/<SCAN_RESULT_TOPIC_NAME>

provider:
  name: google
  stage: ${opt:stage, self:custom.defaultStage}
  runtime: python39
  region: ${param:DEPLOYMENT_REGION}
  project: ${param:GCP_PROJECT_ID}
  environment:
    TEAMS_URL: ${param:TEAMS_URL}

frameworkVersion: '3'
plugins:
  - serverless-google-cloudfunctions

package:
  include:
    - "!node_modules/**"
    - "!docs/**"
    - "!.git/**"
  exclude:
    - README.md
    - .gitignore

functions:
  main:
    handler: main
    events:
      - event:
          eventType: ${param:EVENT_TYPE}
          resource: ${param:TRIGGER_RESOURCE}
